env:
  # Telegram
  TG_CHAT: @theunknownname06
  TG_TOKEN: ENCRYPTED[7c2474fd54ef08c99aa039b8934f8371b33cd37617ea7ce502d6165851ed60f6381bed88b7b545b507b2b2fd232a3028]

  # Gitlab
  PUSH_TO_GITLAB: true
  GITLAB_GROUP: TheUnknownName06
  GITLAB_TOKEN: ENCRYPTED[82addb09f14df576aee736e7b51b0e62063d82bcb608d56df937e262b8d021a9903f1f48529b67a85cbbcab849a1019f]
  GITLAB_INSTANCE: gitlab.com

  # Private SSH Key
  PRIV_SSH_KEY: ENCRYPTED[574e1ce28a85c0f2cc95977dbc19593729660c77ead8efdb7f56d0d7b49a68766fa4609f97b74ecd606bd3a08f45f37d]

task:
  name: "Firmware Dump by DumprX x DumpYara"

  #skip: $CIRRUS_BRANCH == 'main'
  #auto_cancellation: $CIRRUS_BRANCH == 'autocancel'
  timeout_in: 120m
  container:
      image: ubuntu:22.04
      privileged: true
      cpu: 4
      memory: 16G

  Clone_script:
      - apt update;apt upgrade -y;apt install wget git curl sudo neofetch python3 python-pip -y
      - git clone --depth=1 --single-branch https://github.com/DumprX/DumprX ~/yara-kit
  
  Set-SSH-Keys_script:
      - mkdir -p ~/.ssh
      - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
      - ssh-keyscan -H "${GITLAB_INSTANCE}" >> ~/.ssh/known_hosts
      - echo "${PRIV_SSH_KEY}" > ~/.ssh/id_ed25519
      - chmod 600 ~/.ssh/id_ed25519

  Setup_script:
      - git config --global user.name "TUNBudi06"
      - git config --global user.email "anjaytun2006@gmail.com"
      - git config --global color.ui auto
      - cd ~/yara-kit
      - echo "${GITLAB_TOKEN}" > .gitlab_token
      - echo "${GITLAB_GROUP}" > .gitlab_group
      - echo "${TG_CHAT}" > .tg_chat
      - echo "${TG_TOKEN}" > .tg_token
      - echo "${GITLAB_INSTANCE}" > .gitlab_instance
      - bash setup.sh

  DumprX_script:
      - cd ~/yara-kit
      - bash dumper.sh $(cat ${CIRRUS_WORKING_DIR}/ROM_URL.txt)
